name: DASH-docker-bmv2-bldr-build-publish-acr


on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-bmv2-bldr-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-bmv2-bldr-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build and publish docker dash-bmv2-bldr image
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-bmv2-bldr docker image
      run: make docker-bmv2-bldr
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DASH_ACR_LOGIN_SERVER }}
        username: ${{ secrets.DASH_ACR_USERNAME }}
        password: ${{ secrets.DASH_ACR_PASSWORD }}    
    - name: Publish dash-bmv2-bldr image
      run: docker push sonicdash.azurecr.io/dash-bmv2-bldr:220630