name: DASH-docker-saithrift-bldr-build-image

on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-saithrift-docker.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-saithrift-docker.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build docker dash-saithrift-bldr image
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-saithrift docker image
      run: make docker-saithrift-bldr
    - name: Publish dash-saithrift docker image
      run: make docker-publish-saithrift-bldr