name: DASH-docker-bmv2-bldr-build-publish-acr

on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-bmv2-bldr-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr'
      - 'dash-pipeline/dockerfiles/DOCKER_BMV2_BLDR_IMG.env'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-bmv2-bldr-docker-acr.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr'
      - 'dash-pipeline/dockerfiles/DOCKER_BMV2_BLDR_IMG.env'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build docker dash-bmv2-bldr image
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-bmv2-bldr docker image
      run: make docker-bmv2-bldr
    - name: Get docker image name:tag from env file
      run: make docker-save-bmv2-bldr
    - name: Upload Docker image artifact for publishing job
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: bmv2-bldr-image.tar
        retention-days: 1      
  publish:
    name: Publish docker dash-bmv2-bldr image
    if: github.repository == 'Azure/DASH'
    runs-on: ubuntu-20.04
    needs: build
    defaults:
      run:
        working-directory: ./dash-pipeline
      # Load and un-archive the Docker image
    steps:
    - uses: actions/checkout@v3
    - name: Download Docker image artifact for publishing job
      uses: actions/download-artifact@v2
      with:
        name: docker-image
    - name: Load Docker image artifact
      run: make docker-load-bmv2-bldr
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DASH_ACR_LOGIN_SERVER }}
        username: ${{ secrets.DASH_ACR_USERNAME }}
        password: ${{ secrets.DASH_ACR_PASSWORD }}    
    - name: Publish dash-bmv2-bldr image
      run: make docker-publish-bmv2-bldr
