name: DASH-docker-grpc1.43.2-build-image


on:
  push:
    branches: [ "**" ]
    paths:
      - '.github/workflows/dash-grpc1.43.2-docker.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.grpc1.43.2'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/dash-grpc1.43.2-docker.yml'
      - 'dash-pipeline/dockerfiles/Dockerfile.grpc1.43.2'
      - 'dash-pipeline/.dockerignore'
      - 'dash-pipeline/dockerfiles/.dockerignore'
  workflow_dispatch:

jobs:
  build:
    name: Build docker dash-grpc1.43.2 image
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dash-pipeline
    steps:
    - uses: actions/checkout@v3
    - name: Build dash-grpc1.43.2 docker image
      run: make docker-dash-grpc
    - name: Publish dash-bmv2 docker image
      run: make docker-publish-dash-grpc